global:
  scrape_interval: 10s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'localhost:9093'

rule_files:
  - rules.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - 'localhost:9090'

  - job_name: node
    static_configs:
      - targets:
          - '172.16.0.180:9100'

  - job_name: blackbox_exporter
    static_configs:
      - targets:
          - 'localhost:9115'

  - job_name: blackbox-http
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - 'https://www.baidu.com'
          - 'https://prometheus.io'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: '127.0.0.1:9115'

  - job_name: blackbox-ssh
    metrics_path: /probe
    params:
      module: [ssh_banner]
    static_configs:
      - targets:
          - '172.16.0.180:22'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: '127.0.0.1:9115'

  - job_name: blackbox-icmp
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets:
          - 'www.baidu.com'
          - '172.16.0.180'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: '127.0.0.1:9115'

  - job_name: mysqld_exporter
    static_configs:
      - targets:
          - '172.16.0.180:9104'

  - job_name: process-exporter
    static_configs:
      - targets:
          - '172.16.0.180:9256'

  - job_name: redis_exporter
    static_configs:
      - targets:
          - 'redis://172.16.0.180:6379'
    metrics_path: /scrape
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: '172.16.0.180:9121'

  - job_name: pushgateway
    honor_labels: true  # 不覆盖批处理作业的原标签
    static_configs:
      - targets:
          - 'localhost:9091'
