volumes:
  mysqld_data: {}
networks:
  monitoring:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/24
services:
  mysqld:
    image: 'mysql:5.7'
    volumes:
      - './mysql:/etc/mysql/conf.d'
      - 'mysqld_data:/var/lib/mysql'
      - './init.sql:/docker-entrypoint-initdb.d/init.sql'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    networks:
      - monitoring
    ports:
      - '3306:3306'
  mysqld-exporter:
    image: 'prom/mysqld-exporter:v0.15.0'
    command:
      - '--collect.info_schema.innodb_metrics'
      - '--collect.info_schema.innodb_tablespaces'
      - '--collect.perf_schema.eventsstatementssum'
      - '--collect.perf_schema.memory_events'
      - '--collect.global_status'
      - '--collect.engine_innodb_status'
      - '--collect.binlog_size'
      - '--mysqld.address=mysqld:3306'
      - '--mysqld.username=exporter'
    environment:
      MYSQLD_EXPORTER_PASSWORD: exporter
    ports:
      - '9104:9104'
    networks:
      - monitoring
    depends_on:
      - mysqld